name: Deploy when PR is merged to main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install pnpm
        run: npm install -g pnpm

      # - name: Cache pnpm modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.pnpm-store
      #     key: ${{ runner.OS }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
      #     restore-keys: |
      #       ${{ runner.OS }}-pnpm-
            
      - name: Install Dependencies
        run: pnpm install

      - name: build
        run: pnpm run build

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER_HOST }} "rm -rf ${{ secrets.PATH }}/*"
          scp -r dist/ ${{ secrets.DEPLOY_USER_HOST }}:${{ secrets.PATH }}
